### PR TITLE
New styles

### PR DESCRIPTION
**Pull request by lukehefson**
So I played around with the design a bit and came up with this:

simple-speed-new

…and then tweaked the CSS in firebug until it looked pretty much the same. Then I copied out the CSS from firebug and it was totally messed up. I suck at CSS. I have no idea what happened and I can't seem to debug the issues. Can anyone help?

### CODE REVIEW

**Comment by raucao** [comment]
Uhm, were the issues resolved before that merge? Before merging PRs, please make sure there's at least one other person who comments that the changes are reviewed and working. I'll reset the master for now.

**Comment by lukehefson** [comment]
No, the issues weren't resolved. Sorry, I should have communicated that it was a WIP (work in progress) and added a 'Do not merge' comment.

**Comment by raucao** [comment]
Ok, thanks. I'll check it out then.

**Comment by lukehefson** [comment]
@skddc Thanks but (fingers crossed) I think I've figured out the issues myself. Update coming :soon:

**Pull request merged**
