### PR TITLE
Tweak new style

### PR DESCRIPTION
**Pull request by lukehefson**
Lots of little tweaks to the new design as it looks as though some of my changes broke when the design was updated.

### CODE REVIEW

**Comment by raucao** [comment]
I implemented the new CSS without merging, because you didn't account for small screens, so it was easier for me to incorporate your design ideas from scratch instead of merging and fixing.

Actually, I like it much better with more whitespace and smaller font sizes. Don't you?

I'd definitely tweak the number panels a little more according to your design, but I personally would like to keep the rest as it is. Anyone else has any opinions on this?

**Comment by lukehefson** [comment]
> you didn't account for small screens, so it was easier for me to incorporate your design ideas from scratch instead of merging and fixing.

Ah, my bad. I was unsure how to do the CSS for small screens. Thanks for picking through it and fixing!

My intention with the reduced container width and bigger font sizes was to make the padding around the type consistently weighted so that the app appears to be more of a 'card' than a 'site'. But we should totally discuss the pros/cons of this!

I definitely think that 'kb/s' should be lowercase Helvetica rather than Palatino either way.

**Comment by raucao** [comment]
Changed the numbers as per your suggestion. Like it much better as well.

**Comment by lukehefson** [comment]
_Closing as there's no reason to keep this PR open :smile:_

**Comment by raucao** [comment]
:)

**Pull request closed without merging**
